### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by three18ti** [SValkanov/wifivoid#2]
https://github.com/SValkanov/wifivoid/blob/master/lib/hash_patch.rb

A) Generally speaking, it's not a good idea to monkey patch core classes.  If you know what you're doing, you're aware of the dragons that lie that way... if you don't, beware, that way leads to nothing but dragons...

B) You don't ever actually use this method as far as I can tell, so there's no reason to have it included and it should be removed anyway.

c) I'm not sure this even does what you expect... but without unit tests, it's kinda hard to say.

**Comment by SValkanov** [comment]
The method is used.
